-- Rutin — Ek motivasyon cümleleri
-- Kaynak: kullanıcının verdiği 140+ motivasyon/disiplin/spor sözü listesi.
-- Sadece INSERT içerir, mevcut motivation_contents satırlarına dokunmaz.
-- Tekrar çalıştırılırsa aynı sözler ikinci kez eklenir — bu yüzden SADECE
-- BİR KEZ çalıştırılmalıdır (idempotent değildir, kasıtlı olarak).

insert into public.motivation_contents (image_url, quote, category) values
  ('', 'Zafer, zafer benimdir diyebilenindir. Başarı ise “başaracağım” diye başlayarak sonunda “başardım” diyenindir.', 'discipline'),
  ('', 'Kazanma isteği ve başarıya ulaşma arzusu birleşirse kişisel mükemmelliğin kapısını açar.', 'discipline'),
  ('', 'Hiçbir şeyden vazgeçme, çünkü sadece kaybedenler vazgeçer.', 'discipline'),
  ('', 'Başarıya çıkan asansör bozuk. Bekleyerek zaman kaybetmeyin, adım adım merdivenleri çıkmaya başlayın.', 'discipline'),
  ('', 'Fırsatlar durup dururken karşınıza çıkmaz, onları siz yaratırsınız.', 'discipline'),
  ('', 'Şansa çok inanırım ve ne kadar çok çalıştıysam ona o kadar çok sahip oldum.', 'discipline'),
  ('', 'Bir şeye başlayıp başarısız olmaktan daha kötü tek şey hiçbir şeye başlamamaktır.', 'discipline'),
  ('', 'Sadece sınırlarını aşmanın riskini alanlar ne kadar ileri gidebildiklerini görürler.', 'discipline'),
  ('', 'Hayat her ne kadar zor görünse de, yapabileceğimiz ve başarabileceğimiz bir şey mutlaka vardır.', 'discipline'),
  ('', 'Bir şeyi başarmak ne kadar zorsa, zaferin tadı o kadar güzeldir.', 'discipline'),
  ('', 'Hiç kimse başarı merdivenine elleri cebinde tırmanmamıştır.', 'discipline'),
  ('', 'Ne zaman başarılı bir iş görseniz, birisi bir zamanlar mutlaka cesur bir karar almıştır.', 'discipline'),
  ('', 'Sessizce sıkı çalışın, bırakın başarı sesiniz olsun.', 'discipline'),
  ('', 'Eğer her şey kontrol altında gibi görünüyorsa, yeterince hızlı gitmiyorsunuzdur.', 'discipline'),
  ('', 'Başarısız insanlar içerisinde bulundukları duruma göre karar verirler. Başarılı insanlar ise olmak istedikleri yere göre karar verirler.', 'discipline'),
  ('', 'Sadece başarılı bir insan olmaya değil, değerli bir insan olmaya çalışın.', 'discipline'),
  ('', 'Başarı son değildir, başarısızlık ise ölümcül değildir: Önemli olan ilerlemeye cesaret etmektir.', 'discipline'),
  ('', 'Başarı, küçük çabaların her gün tekrarlanmasıyla gelir.', 'discipline'),
  ('', 'İmkansız, sadece cesaretini yeterince toplayamayanlar için bir kelimedir.', 'discipline'),
  ('', 'Bugün ter dökmeyen, yarın zaferi kutlayamaz.', 'discipline'),
  ('', 'Hayallerini gerçeğe dönüştürmenin ilk adımı uyanmaktır.', 'discipline'),
  ('', 'Başarı, en yükseğe sıçrayabilen değil; yere her düştüğünde kalkabilendir.', 'discipline'),
  ('', 'Yapabileceğine inanırsan, yol zaten açılır.', 'discipline'),
  ('', 'Başarı, hazır olanlara değil; harekete geçenlere gelir.', 'discipline'),
  ('', 'Sınırlar, genellikle sadece bizim zihnimizdedir.', 'discipline'),
  ('', 'Her büyük başarı, bir hayalle başlar. O hayale sarıl.', 'discipline'),
  ('', 'Zor zamanlar asla kalıcı değildir ama zorluklara direnen insanlar kalıcıdır.', 'discipline'),
  ('', 'Hayatımı sadece ben değiştirebilirim. Kimse benim için bunu yapmaz.', 'discipline'),
  ('', 'Hiç kimse geriye gidip yeni bir başlangıç yapamaz ama bugün yeni bir son yapıp yeniden başlayabilir.', 'discipline'),
  ('', 'Diğerlerinden daha akıllı olmak zorunda değiliz. Diğerlerinden daha disiplinli olmak zorundayız.', 'discipline'),
  ('', 'Uyandığınızda; yaşamanın, zevk almanın, düşünmenin ve sevmenin ne kadar büyük bir ayrıcalık olduğunu hatırlayın.', 'discipline'),
  ('', 'Siz kendinize inanın, başkaları da size inanacaktır.', 'discipline'),
  ('', 'Karanlıktan korkan bir çocuğu kolayca affedebiliriz. Hayatın gerçek trajedisi büyükler ışıktan korktuğunda başlar.', 'discipline'),
  ('', 'Dünyayı değiştirebilen insanla buna inanacak kadar deli olanlardır.', 'discipline'),
  ('', 'Sadece görülmeyeni gören imkansızı başarabilir.', 'discipline'),
  ('', 'Her gün kendini yeniliyorsun. Bazen başarılı olursun, bazen olamazsın, ama önemli olan ortalamadır.', 'discipline'),
  ('', 'Kısa vadede acımasızca dürüst olun, uzun vade için ise iyimser ve kendinizden emin olun.', 'discipline'),
  ('', 'Birisi size bir şeyi yapamayacağını söylediğinde, belki de size sadece kendi yapamadıklarını söylüyordur.', 'discipline'),
  ('', 'Kendinizi sınırlamayın. Çoğu insan yapabileceklerini düşündükleri şeyler konusunda kendilerini sınırlarlar. Sadece zihninizin gidebildiği kadar ileriye gidebilirsiniz. Neye inanırsanız, onu yapabilirsiniz.', 'discipline'),
  ('', 'Zeki insanlar herkesten ve her şeyden öğrenirler. Ortalama insanlar deneyimlerinden öğrenirler. Aptal insanlar ise zaten bütün cevaplara sahiptir.', 'discipline'),
  ('', 'Bardağın yarısının dolu mu, boş mu olduğunu tartışan insanlar asıl odaklanmaları gereken noktayı kaçırıyorlar. Bardak doldurulabilir.', 'discipline'),
  ('', 'Yüzünüzü güneşe çevirin, böylece gölgeler her zaman arkanızda kalacaktır.', 'discipline'),
  ('', 'Dün zekiydim, bu yüzden dünyayı değiştirmek istedim. Şimdi ise bilgeyim, bu sebeple kendimi değiştiriyorum.', 'discipline'),
  ('', 'Eğer bir şeyi değiştiremiyorsanız bırakın. Değiştiremediğiniz şeylerin mahkûmu olmayın.', 'discipline'),
  ('', 'Dışarıda olanları her zaman kontrol edemezsiniz. Ama içinde olanları edebilirsin.', 'discipline'),
  ('', 'En büyük düşmanınızın iki kulağınızın arasında yaşamadığına emin olun.', 'discipline'),
  ('', 'Dünden ders alın, bugün için yaşayın, yarın için umutlu olun.', 'discipline'),
  ('', 'Hayatta en büyük keşif, bir insanın kendi potansiyelini fark etmesidir.', 'discipline'),
  ('', 'Kendine liderlik edemeyen biri, başkalarını da yönlendiremez.', 'discipline'),
  ('', 'Her büyük değişim, küçük bir kararla başlar.', 'discipline'),
  ('', 'Başarılı insanlar güçlü yönlerine odaklanır, zayıflıkları üzerinde takılı kalmaz.', 'discipline'),
  ('', 'Başkalarının seni nasıl gördüğü değil, senin kendini nasıl gördüğün hayatını şekillendirir.', 'discipline'),
  ('', 'Kendini tanımak, tüm bilgeliğin başlangıcıdır.', 'discipline'),
  ('', 'Eğer zorlanmıyorsanız, değişemezsiniz.', 'discipline'),
  ('', 'Bundan bir yıl sonra, bugün başlamış olmayı dileyeceksin', 'discipline'),
  ('', 'Aynaya bakın. İşte kendinizi kıyaslamanız gereken tek kişi orada.', 'discipline'),
  ('', 'Sağlam kafa, sağlam vücutta bulunur.', 'discipline'),
  ('', 'Spor yapmak kraldır. Beslenme ise kraliçedir. İkisini bir araya koyarsanız ise bir krallığınız olur.', 'discipline'),
  ('', 'Disiplin, hedefler ve başarılar arasındaki köprüdür.', 'discipline'),
  ('', 'Bugün hissettiğin acı, yarın hissettiğin güç olacak.', 'discipline'),
  ('', 'Şampiyon, ayağa kalkamayacak gibi hissettiği zaman, ayağa kalkan kişidir.', 'discipline'),
  ('', 'Kan, ter ve saygı. İlk ikisini verir, üçüncüsünü kazanırsınız.', 'discipline'),
  ('', 'Kaslarınız ve zihniniz birlikte çalışmalı. Birisi olmadan diğeri hiçbir işe yaramaz.', 'discipline'),
  ('', 'Antrenmanın her dakikasından nefret ettim, ama durmadan şunu düşündüm “Pes etme. Şimdi acı çek ve hayatının geri kalanını şampiyon olarak yaşa.”', 'discipline'),
  ('', 'Spor yaparken savaştığınız direnç ve hayat için mücadele ederken savaştığınız direnç güçlü bir karakteri inşa eden yapı taşlarıdır.', 'discipline'),
  ('', 'Gerçek antrenman, durmak istediğiniz zaman başlar.', 'discipline'),
  ('', 'Altın madalyalar her gün spor salonunda sarf edilen terden, kandan, göz yaşından ve efordan oluşurlar.', 'discipline'),
  ('', 'Yeteneğin seni zirveye taşıyabilir ama orada kalmanı sağlayan karakterindir.', 'discipline'),
  ('', 'Yorgun olduğunda değil, işin bittiğinde dur.', 'discipline'),
  ('', 'Bugün acı çekmek, yarın daha iyi olmak içindir.', 'discipline'),
  ('', 'Başarı, küçük bir şeyin doğru şekilde tekrar tekrar yapılmasıdır.', 'discipline'),
  ('', 'Zihniniz sizi ya sınırlandırır ya da özgürleştirir.', 'discipline'),
  ('', 'Benden yetenekli olabilirler ama kimse benden daha çok çalışamaz.', 'discipline'),
  ('', 'Kazanmak bir alışkanlıktır; ne yazık ki kaybetmek de öyle.', 'discipline'),
  ('', 'Başarı için gizli bir formül yok. Bu; ter, azim ve kararlılıkla ilgili.', 'discipline'),
  ('', 'Asla pes etmeyin. Bugünün acısı, yarının zaferidir.', 'discipline'),
  ('', 'Her antrenman sizi, hayal ettiğiniz kişiye bir adım daha yaklaştırır.', 'discipline'),
  ('', 'Rakibim kim olursa olsun, ben her zaman en iyisi olmak için çalışırım.', 'discipline'),
  ('', 'Ben yetenekli doğmadım. Yetenekli olmak için her gün çalıştım.', 'discipline'),
  ('', 'Zor zamanlar, güçlü insanlar yaratır.', 'discipline'),
  ('', 'Acı geçicidir. Pes edersen, sonsuza kadar kalır.', 'discipline'),
  ('', 'Hiçbir şey için hazır olmazsınız. Sadece başlarsınız.', 'discipline'),
  ('', 'İmkânsız diye bir şey yok. Bu sadece büyük olasılıkların daha uzun sürdüğünü gösterir.', 'discipline'),
  ('', 'Hayal ettiğim hayatı kazanmak için her gün savaşıyorum.', 'discipline'),
  ('', 'Güçlü olan, en çok kazanan değil; her düşüşten sonra ayağa kalkandır.', 'discipline'),
  ('', 'Antrenmanlar acı verebilir ama zafer her şeyi unutturur.', 'discipline'),
  ('', 'Zafere giden yol; disiplin, özveri ve tekrar tekrar çalışmaktan geçer.', 'discipline'),
  ('', 'Oturduğumuz sürece korkular yaratırız. Harekete geçtiğimizde ise korkularımızın üstesinden geliriz', 'discipline'),
  ('', 'Senin almaya cesaret edemediğin riskleri alanlar, senin yaşamak istediğin hayatı yaşarlar.', 'discipline'),
  ('', 'Bir gün kalkacaksınız ve hep hayal ettiğiniz şeyleri yapmaya vakit kalmamış olacak. Şimdi harekete geçmenin tam zamanı.', 'discipline'),
  ('', 'Yapmadığım şeyler yüzünden pişmanlık duymaktansa, yaptığım şeyler yüzünden pişmanlık duymayı tercih ederim.', 'discipline'),
  ('', 'Sadece düşünerek bir tarlayı biçemezsiniz. Başlamak istiyorsanız, başlamanız lazım.', 'discipline'),
  ('', 'Kurallara uyarak yürümeyi öğrenemezsin. Yaparak ve düşünerek öğrenirsin.', 'discipline'),
  ('', 'Düşünmeden bir gün bile geçiremediğiniz bir şeyden asla vazgeçmeyin.', 'discipline'),
  ('', 'Unutma, her şampiyon bir zamanlar pes etmeyi reddeden bir yarışmacıydı.', 'discipline'),
  ('', 'Aynı bölümü tekrar tekrar okumaya devam edersen hayatının bir sonraki bölümüne başlayamazsın.', 'discipline'),
  ('', 'Başlamanın yolu, konuşmayı bırakıp yapmaya başlamaktır.', 'discipline'),
  ('', 'Bin kilometrelik bir yolculuk tek bir adımla başlar.', 'discipline'),
  ('', 'Öne geçmenin sırrı, başlamaktır.', 'discipline'),
  ('', 'Ağaç dikmek için en iyi zaman 20 yıl öncesiydi. İkinci en iyi zaman ise şimdi.', 'discipline'),
  ('', 'Bütün merdivenleri görmek zorunda değilsiniz. Yapmanız gereken tek şey ilk adımı atmak.', 'discipline'),
  ('', 'Başlamak için mükemmel olmak zorunda değilsiniz, ama mükemmel olmak için önce başlamalısınız.', 'discipline'),
  ('', 'Bugün içinde bulunduğunuz mücadele, yarın ihtiyacınız olan gücü geliştiriyor.', 'discipline'),
  ('', 'Hayat her ne kadar zor görünse de, yapabileceğiniz ve başarabileceğiniz bir şey her zaman vardır.', 'discipline'),
  ('', 'Çatışman ne kadar zorsa, zaferin de o kadar şereflidir!', 'discipline'),
  ('', 'Yüzüstü yere serilseniz bile, hala ileriye doğru hareket ediyorsunuzdur!', 'discipline'),
  ('', 'Tanrıdan kolay bir hayat dilemeyin: zor olana dayanabilecek güç dileyin.', 'discipline'),
  ('', 'Bir gün geçmişe baktığınızda en güzel yıllarınızın mücadele ile geçen yıllar olduğunu göreceksiniz.', 'discipline'),
  ('', 'Girmeye korktuğun mağara, umduğun hazineyi saklıyor olabilir.', 'discipline'),
  ('', 'Mağlubiyete uğrayınca ümitsizliğe kapılma, her başarısızlıkta bir zafer arzusu yatar.', 'discipline'),
  ('', 'Yüzleşmediğimiz korkularımız sınırlarımızı oluşturur.', 'discipline'),
  ('', 'Zorluklarla karşılaşmak istemeyenler, felaketlere layıktır.', 'discipline'),
  ('', 'Dünya herkesi kırar ve bazıları kırılan yerlerinden güçlenir.', 'discipline'),
  ('', 'Acı sizi değiştirebilir ancak bu değişim kötü olmak zorunda değildir. Acıyı alın ve bilgeliğe dönüştürün.', 'discipline'),
  ('', 'Eğer insanlar ne kadar ileri gidebileceğinizi sorguluyorsa, onları duyamayacağınız kadar ileriye gidin.', 'discipline'),
  ('', 'İnsanları güçlendiren şey, zor günlerdir.', 'discipline'),
  ('', 'Zorluklarınızı sınırlamayın. Sınırlarınızı zorlayın.', 'discipline'),
  ('', 'Yenilmek geçici bir durumdur. Pes etmek ise onu kalıcı yapar.', 'discipline'),
  ('', 'Bazen karanlık bir yerdeyken gömüldüğünüzü düşünürsünüz. Ama aslında ekilmişsinizdir.', 'discipline'),
  ('', 'Vaktinde bana “hayır” diyen herkese minnettarım. Onlar sayesinde kendi işimi kendim yapabiliyorum.', 'discipline'),
  ('', 'Pes etmeyi düşündüğünüzde, hala haksız çıkarmanız gereken insanlar olduğunu hatırlayın.', 'discipline'),
  ('', 'En büyük makam, en büyük hak çalışanlara ait olacaktır.', 'discipline'),
  ('', 'Başarı, öğrenmeye olan bağlılığın bir ürünüdür. Her gün biraz daha öğren.', 'discipline'),
  ('', 'Ne kadar çok öğrenirsen, o kadar çok yer gezmiş gibi olursun.', 'discipline'),
  ('', 'Disiplin, öğrenmenin köprüsüdür. Bilgiyi alışkanlığa dönüştürür.', 'discipline'),
  ('', 'Zeki insan öğrenmeyi bırakmaz; sadece nasıl öğrendiğini geliştirir.', 'discipline'),
  ('', 'Zorluklar öğrenmenin ham maddesidir. Her zor konu seni daha zeki kılar.', 'discipline'),
  ('', 'Her gün bir şey öğrenmeden geçen gün, boşa geçirilmiş bir gündür.', 'discipline'),
  ('', 'Yalnızca bilgiyi isteyenler değil, onu arayanlar gerçekten öğrenir.', 'discipline'),
  ('', 'İrade gücü, bilgiyle birleştiğinde sınırlar ortadan kalkar.', 'discipline'),
  ('', 'Büyük işler, küçük şeyleri iyi yapanlar tarafından başarılır.', 'discipline'),
  ('', 'Her gün tutarlılık ile tekrarlanan küçük disiplinler, zaman içinde büyük başarıların oluşmasını sağlar.', 'discipline'),
  ('', 'Bilginin efendisi olmak için çalışmanın uşağı olmak şarttır.', 'discipline'),
  ('', 'Çalışmak bizi üç beladan kurtarır: Can sıkıntısı, kötü alışkanlıklar ve yoksulluk.', 'discipline'),
  ('', 'İnsanoğlu için en kutsal ibadet; çalışmak, doğruluk ve insan sevgisidir.', 'discipline'),
  ('', '10 bin tekmeyi bir kez çalışandan korkmam, bir tekmeyi 10 bin kez çalışandan korkarım.', 'discipline'),
  ('', 'Çalışma olmadan yetenek hiçbir şeydir.', 'discipline'),
  ('', 'Basit bir adamın elinden gelini yapmaya çalışması, zeki bir adamın tembelliğinden iyidir.', 'discipline'),
  ('', 'Daima yukarıya bak, bilmediğin şeyleri öğren ve her gün yükselmeye çalış.', 'discipline'),
  ('', 'İnsanlar, benim ustalığımı elde etmek için ne kadar sıkı çalıştığımı bilseler, o kadar da hayret edilecek bir şey olmadığını anlarlardı.', 'discipline'),
  ('', 'Zamanlama, azim ve 10 yıl boyunca aralıksız çalışmak, sizi bir gecede başarılı olmuşsunuz gibi gösterir.', 'discipline'),
  ('', 'Eğitim geleceğin pasaportudur, çünkü yarın, bugün hazırlananlara aittir.', 'discipline'),
  ('', 'Dünyayı değiştirmek için kullanabileceğin en güçlü silah eğitimdir.', 'discipline');
